# Generated by Django 4.2.3 on 2023-07-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='numb2',
            field=models.IntegerField(default=4),
        ),
    ]
